"""empty message

Revision ID: 9086565e4bf9
Revises: 1fae91cf9afe
Create Date: 2019-06-23 20:20:25.726030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9086565e4bf9'
down_revision = '1fae91cf9afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('state', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'state')
    # ### end Alembic commands ###
